### ISSUE TITLE
Fetch.post = Uncaught (in promise) Error: Given an invalid JSON: Unexpected end of JSON input

### ISSUE THREAD

**Issue by TheDevKnight** [thoth-org/Thoth.Fetch#16] opened 2020-04-24 21:19 UTC
Hi @MangelMaxime, 

i found the solution for my CORS problem and was able to get my data from the rest service. 
I implement the post after the succeeded get. And this call works in my app

`let addKonto (konto:Konto) = Fetch.post ("https://smuckster.azurewebsites.net/konten", konto) |> ignore`

but i see in the developer console, this error

`Uncaught (in promise) Error: Given an invalid JSON: Unexpected end of JSON input`

strange is, that the call is succed and the data is send correct to the rest service. 

My type konto looks like this

`type KontoId = int`

`type Konto = {
    Id: KontoId
    Name: string
    AppId: string
    DevId: string
    CertId: string
}`

and this is the value that was send 

`{
    "Id": 0,
    "Name": "Test",
    "AppId": "A",
    "DevId": "B",
    "CertId": "C"
}`

The post works, but i dont know why these error appears :/

Regards

**Comment by MangelMaxime** [comment] 2020-04-26 13:10
Hello,

happy that you solved your problem.

I think you see this error because your API is sending an empty body as a response and because you are discarding the result with `ignore`. This probably makes the type inference fail and Thoth.fetch don't know it should look for a `unit` result and so is trying to retrieve the JSON from the body but because there is no body it fails.

In general, I use promise CE as shown in the documentation [here](https://thoth-org.github.io/Thoth.Fetch/#Successful-request).

Perhaps, forcing the inference will work:

```fs
let addKonto (konto:Konto) = Fetch.post<unit> ("https://smuckster.azurewebsites.net/konten", konto) |> ignore
```

**Comment by TheDevKnight** [comment] 2020-04-27 06:05
Hi,

thank your for the hin, that empty body sounds logic. 

But 

`let addKonto  (konto:Konto) = Fetch.post<unit> ((getUrl "konten"), konto) |> ignore`

will produce the following error 

`The member or object constructor 'post' does not take 2 argument(s). An overload was found taking 4 arguments.`

So i try the code from the docu

`let addKonto (konto:Konto) = 
    promise {
        do! Fetch.post ((getUrl "konten"), konto)
    }`

but i still get the error

`Uncaught (in promise) Error: Given an invalid JSON: Unexpected end of JSON input`

The type inference looks ok for me

`Konto -> Fable.Core.JS.Promise<unit>`

Regards

**Comment by MangelMaxime** [comment] 2020-04-27 07:05
Hum, because you are passing a data argument to `Fetch.post` you should indeed use `Fetch.post<_, unit>` if I remember correctly. You can check the documentation for that.

In order to help you, I will need a minimal reproduction code because like that I can't explore the problem. Or if you can provide a failing test it would be perfect because `unit` response are being tested [here for an example](https://github.com/thoth-org/Thoth.Fetch/blob/master/tests/Main.fs#L755-L762) and it is working.

**Comment by TheDevKnight** [comment] 2020-04-27 12:21
Hi Maxime,

here is a sample 

https://github.com/TheDevKnight/SafeStackTest

you can run the app with 

`dotnet fake build --target run`

click on Add Konto and you see the Exception in den Developer Console (F12)

Thanks for your help

Regards

**Comment by MangelMaxime** [comment] 2020-04-27 13:32
Hello @TheDevKnight,

thank you for the repo.

You are using Thoth.Fetch 1.1 while support for `unit` has been added to version 2 of the library.

You need to upgrade Thoth.Fetch, then it should in theory work.

**Comment by TheDevKnight** [comment] 2020-04-27 19:21
Oh man 🙄 thank you for the hint. My start into F# web Dev was to create a simple template App with safe template.

Has version 2 breaking changes?

I will give the Safe guys the tip to update your package. 

One last question 😉 is it uncommen to have an empty body in the response of a POST request?

Regards

**Comment by MangelMaxime** [comment] 2020-04-27 19:59
Hum, yes version 2 does have breakings changes.

The breaking changes are because now, it is returning more specialized errors and also it's treating `unit` as a special case when no body is received.

About your question, I don't know. In general, when I create a resource I return it or at least it's ID. Because then I go forward to a "Show" view or something.

I am closing this issue as the problem is because of using the wrong version of the library.

**Closed by MangelMaxime** 2020-04-27 19:59 UTC
